"""add username and name fields to user profile

Revision ID: 3ef3fbab27c7
Revises: 7d4f3b55f569
Create Date: 2025-12-12 20:42:08.791405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef3fbab27c7'
down_revision: Union[str, None] = '7d4f3b55f569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_profiles_username'), 'user_profiles', ['username'], unique=False)
    op.drop_column('user_profiles', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_profiles_username'), table_name='user_profiles')
    op.drop_column('user_profiles', 'last_name')
    op.drop_column('user_profiles', 'first_name')
    op.drop_column('user_profiles', 'username')
    # ### end Alembic commands ###
